version: "2"
services:
  ui:
    network_mode: "host"
    ports:
      - 3000:3000
    image: "node:12"
    working_dir: "/srv"
    command: ["yarn", "start"]
    environment:
      PATH: "/srv/node_modules/.bin:$PATH"
    volumes:
      - "./ui:/srv"
      - "./.cache:/home/node/.cache"
  api:
    network_mode: "host"
    ports:
      - 4000:4000
    image: "node:12"
    working_dir: "/srv"
    command: ["yarn", "start"]
    environment:
      PATH: "/srv/node_modules/.bin:$PATH"
    volumes:
      - "./api:/srv"
      - "./.cache:/home/node/.cache"
  cypress:
    network_mode: "host"
    image: "cypress/included:4.8.0"
    environment:
      PATH: "/e2e/node_modules/.bin:$PATH"
    shm_size: 2g
    working_dir: "/e2e"
    depends_on:
      - api
      - ui
    volumes:
      - "./ui:/e2e"
      - "./.cache:/home/node/.cache"
